services:
  backend:
    build:
      context: ./backend-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend-server/.env
    volumes:
      - ./backend-server:/app

  frontend:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./website/.env
    volumes:
      - ./website:/app
      - /app/node_modules 
    depends_on:
      - backend

  database:
    image: mongo
    ports:
      - "27017:27017"